// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOnKHR3J1XAeSHm_rwthkMelo077ym0m0',
    appId: '1:74532789734:web:a1fbe3e57579d1e7cf8a27',
    messagingSenderId: '74532789734',
    projectId: 'akilligardirobum',
    authDomain: 'akilligardirobum.firebaseapp.com',
    storageBucket: 'akilligardirobum.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf_FdrzVlHbUPWKcpP6U94qpisvyrw06Y',
    appId: '1:74532789734:android:26cf2e546d8e41e8cf8a27',
    messagingSenderId: '74532789734',
    projectId: 'akilligardirobum',
    storageBucket: 'akilligardirobum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXEWb3_8ubud2A3CqQG0CiPGjiBinKKtM',
    appId: '1:74532789734:ios:90e0d2f5d0f8cb7dcf8a27',
    messagingSenderId: '74532789734',
    projectId: 'akilligardirobum',
    storageBucket: 'akilligardirobum.firebasestorage.app',
    iosBundleId: 'com.example.kombinimCepte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXEWb3_8ubud2A3CqQG0CiPGjiBinKKtM',
    appId: '1:74532789734:ios:90e0d2f5d0f8cb7dcf8a27',
    messagingSenderId: '74532789734',
    projectId: 'akilligardirobum',
    storageBucket: 'akilligardirobum.firebasestorage.app',
    iosBundleId: 'com.example.kombinimCepte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOnKHR3J1XAeSHm_rwthkMelo077ym0m0',
    appId: '1:74532789734:web:e888cc2e75ac07aacf8a27',
    messagingSenderId: '74532789734',
    projectId: 'akilligardirobum',
    authDomain: 'akilligardirobum.firebaseapp.com',
    storageBucket: 'akilligardirobum.firebasestorage.app',
  );
}
