class WardrobeMetadata {
  static const List<String> categories = [
    'Üst',
    'Alt',
    'Elbise',
    'Takım',
    'Dış Giyim',
    'Ayakkabı',
    'İç Giyim',
    'Gece Giyim',
    'Spor Giyim',
    'Ev Giyim',
    'Plaj Giyim',
    'Çanta',
    'Takı',
    'Baş Aksesuarı',
    'Boyun Aksesuarı',
    'Bel Aksesuarı',
    'El Aksesuarı',
    'Gözlük',
  ];

  static const Map<String, List<String>> subcategoryMap = {
    'Üst': [
      'Tişört',
      'Gömlek',
      'Bluz',
      'Body',
      'Büstiyer',
      'Crop Top',
      'Kazak',
      'Hırka',
      'Sweatshirt',
      'Hoodie',
      'Tunik',
      'Polo',
      'Atlet',
      'Yelek',
      'Bodysuit',
      'Triko Üst',
    ],
    'Alt': [
      'Jean',
      'Pantolon',
      'Kumaş Pantolon',
      'Bol Pantolon',
      'Kargo Pantolon',
      'Eşofman Altı',
      'Şort',
      'Bermuda',
      'Etek',
      'Mini Etek',
      'Midi Etek',
      'Maxi Etek',
      'Tayt',
      'Legging',
      'Kapri',
    ],
    'Elbise': [
      'Günlük Elbise',
      'Mini Elbise',
      'Midi Elbise',
      'Maxi Elbise',
      'Abiye',
      'Kokteyl Elbisesi',
      'Gömlek Elbise',
      'Triko Elbise',
      'Slip Elbise',
      'Tulum',
      'Salopet',
    ],
    'Takım': [
      'Takım Elbise',
      'Blazer Takım',
      'Eşofman Takımı',
      'Şort Takımı',
      'Triko Takım',
      'Pijama Takımı',
      'Yelek Takım',
    ],
    'Dış Giyim': [
      'Ceket',
      'Blazer',
      'Mont',
      'Kaban',
      'Palto',
      'Trençkot',
      'Yağmurluk',
      'Parka',
      'Bomber Ceket',
      'Deri Ceket',
      'Kot Ceket',
      'Şişme Mont',
      'Şişme Yelek',
      'Panço',
    ],
    'Ayakkabı': [
      'Sneaker',
      'Spor Ayakkabı',
      'Koşu Ayakkabısı',
      'Topuklu Ayakkabı',
      'Loafer',
      'Babet',
      'Balerin Ayakkabı',
      'Oxford',
      'Mokasen',
      'Bot',
      'Çizme',
      'Postal',
      'Sandalet',
      'Terlik',
      'Ev Terliği',
    ],
    'İç Giyim': [
      'Sütyen',
      'Bralet',
      'Külot',
      'Boxer',
      'Atlet',
      'Korse',
      'Termal İçlik',
      'Çorap',
      'Kilotlu Çorap',
    ],
    'Gece Giyim': [
      'Pijama Takımı',
      'Gecelik',
      'Sabahlık',
      'Uyku Şortu',
      'Uyku Tişörtü',
    ],
    'Spor Giyim': [
      'Spor Tişört',
      'Spor Tayt',
      'Antrenman Üstü',
      'Koşu Şortu',
      'Spor Sütyeni',
      'Yoga Üstü',
      'Yoga Taytı',
      'Outdoor Pantolon',
    ],
    'Ev Giyim': [
      'Ev Elbisesi',
      'Ev Tişörtü',
      'Ev Şortu',
      'Eşofman',
      'Sabahlık',
    ],
    'Plaj Giyim': [
      'Mayo',
      'Bikini',
      'Pareo',
      'Plaj Elbisesi',
      'Plaj Şortu',
      'Kaftan',
      'Kimono',
    ],
    'Çanta': [
      'Omuz Çantası',
      'Sırt Çantası',
      'Clutch',
      'Bel Çantası',
      'Tote Çanta',
      'Laptop Çantası',
      'Valiz',
      'Mini Çanta',
    ],
    'Takı': [
      'Kolye',
      'Bileklik',
      'Yüzük',
      'Küpe',
      'Broş',
      'Saat',
      'Halhal',
    ],
    'Baş Aksesuarı': [
      'Şapka',
      'Bere',
      'Bandana',
      'Taç',
      'Toka',
    ],
    'Boyun Aksesuarı': [
      'Atkı',
      'Fular',
      'Şal',
      'Kravat',
      'Papyon',
    ],
    'Bel Aksesuarı': [
      'Kemer',
      'Korse Kemer',
      'Bel Çantası',
    ],
    'El Aksesuarı': [
      'Eldiven',
      'Bileklik',
      'Saat',
    ],
    'Gözlük': [
      'Güneş Gözlüğü',
      'Numaralı Gözlük',
      'Koruyucu Gözlük',
    ],
  };

  static const List<String> colors = [
    'Siyah', 'Beyaz', 'Ekru', 'Krem', 'Bej', 'Vizon', 'Camel', 'Kahverengi',
    'Gri', 'Antrasit', 'Gümüş', 'Mavi', 'Lacivert', 'Bebek Mavisi', 'İndigo',
    'Kırmızı', 'Bordo', 'Pembe', 'Fuşya', 'Mor', 'Lila', 'Yeşil', 'Haki',
    'Mint', 'Sarı', 'Hardal', 'Turuncu', 'Mercan', 'Altın', 'Çok Renkli',
    'Desenli',
  ];

  static const List<String> seasons = [
    'Dört Mevsim', 'Yaz', 'Kış', 'İlkbahar', 'Sonbahar'
  ];

  static const List<String> materials = [
    'Pamuk',
    'Organik Pamuk',
    'Keten',
    'Denim',
    'Yün',
    'Merinos Yünü',
    'Kaşmir',
    'İpek',
    'Saten',
    'Deri',
    'Suni Deri',
    'Süet',
    'Polyester',
    'Geri Dönüştürülmüş Polyester',
    'Viskon',
    'Modal',
    'Tencel / Lyocell',
    'Akrilik',
    'Naylon',
    'Elastan',
    'Likra',
    'Kadife',
    'Dantel',
    'Triko',
    'Polar',
    'Kanvas',
    'Jarse',
    'Şifon',
    'Poplin',
    'Gabardin',
    'Kadife',
    'Krep',
    'Müslin',
    'Asetat',
    'Bambu',
    'Vual',
  ];


  static const List<String> washTemperatures = [
    'Makinede yıkanmaz',
    'Soğuk / 20-30°C',
    '30°C',
    '40°C',
  ];

  static const List<String> washMethods = [
    'Nazik makine yıkaması',
    'Normal yıkama',
    'Elde yıkama',
    'Leke bazlı temizlik',
  ];

  static const List<String> dryingMethods = [
    'Asarak kurut',
    'Sererek kurut',
    'Gölgede kurut',
    'Doğal ortamda kurut',
  ];

  static const List<String> ironLevels = [
    'Ütü istemez',
    'Düşük ısı',
    'Orta ısı',
  ];
}
